const collections = [
  { number: '01', title: 'Bridal Heirlooms', copy: 'Hand-finished lehengas, veils and trousseau pieces made for the day—and the generations after.', tone: 'rose' },
  { number: '02', title: 'Groom & Family', copy: 'Sherwanis, bandhgalas and coordinated occasionwear, tailored for a beautifully considered wedding party.', tone: 'gold' },
  { number: '03', title: 'Celebration Edit', copy: 'Distinctive silhouettes for sangeet, mehendi, receptions and every invitation on your calendar.', tone: 'plum' },
];
const steps = [
  ['01', 'Tell us your story', 'Share your occasion, references, colours and timeline with our design team.'],
  ['02', 'Design together', 'We refine the silhouette, fabric and embroidery until every detail feels distinctly yours.'],
  ['03', 'Made for you', 'Your piece is carefully crafted, fitted and finished for an effortless final look.'],
];
export default function Home() {
  return <main>
    <nav className="nav shell" aria-label="Main navigation"><a className="brand" href="#top" aria-label="Regal Embroidery home">RE <span>Regal<br/>Embroidery</span></a><div className="navlinks"><a href="#collections">Collections</a><a href="#process">Our process</a><a href="#about">Our craft</a></div><a className="nav-cta" href="#contact">Book a consultation</a></nav>
    <section className="hero" id="top"><div className="hero-ornament ornament-one"/><div className="hero-ornament ornament-two"/><div className="hero-copy shell"><p className="eyebrow">Made in India · Made for you</p><h1>Clothes for your<br/><em>most beautiful</em> days.</h1><p className="lede">Custom Indian occasionwear, thoughtfully designed and intricately embroidered for weddings, celebrations and everything worth remembering.</p><div className="hero-actions"><a className="button light" href="#contact">Begin your custom piece <span>↗</span></a><a className="text-link" href="#collections">Explore our world <span>↓</span></a></div></div><div className="hero-note"><span>✦</span>Bespoke by appointment<br/>India & worldwide</div></section>
    <section className="intro shell" id="about"><p className="section-kicker">The Regal signature</p><div><h2>Tradition, drawn<br/>in a modern hand.</h2><p>We bring India’s rich embroidery language to contemporary silhouettes. Every piece begins with a conversation and ends with the smallest details considered—from the first sketch to the final hand-finished seam.</p><a className="underlink" href="#process">Discover our process <span>→</span></a></div></section>
    <section className="collections" id="collections"><div className="shell section-head"><div><p className="section-kicker">Designed for the occasion</p><h2>Our collections</h2></div><p>Personal pieces for every person<br/>and every moment of celebration.</p></div><div className="collection-grid shell">{collections.map(item=><article className={`collection-card ${item.tone}`} key={item.title}><div className="textile" aria-hidden="true"><span>✦</span></div><div className="card-copy"><span>{item.number}</span><h3>{item.title}</h3><p>{item.copy}</p><a href="#contact" aria-label={`Enquire about ${item.title}`}>Enquire <b>↗</b></a></div></article>)}</div></section>
    <section className="process shell" id="process"><div><p className="section-kicker">The bespoke experience</p><h2>From first thought<br/>to final fitting.</h2></div><div className="steps">{steps.map(([n,t,c])=><div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{c}</p></div></div>)}</div></section>
    <section className="contact" id="contact"><div className="contact-mark">RE</div><div className="contact-copy"><p className="section-kicker">Your story, beautifully worn</p><h2>Let’s create<br/>something <em>yours.</em></h2><p>Planning a wedding or dressing for a special event? Tell us what you have in mind and we’ll guide you from there.</p><a className="button light" href="mailto:hello@regalemboidery.in?subject=Custom%20design%20consultation">Book your consultation <span>↗</span></a><small>Online and in-person appointments available</small></div></section>
    <footer className="footer shell"><a className="brand footer-brand" href="#top">RE <span>Regal<br/>Embroidery</span></a><div><p>Custom Indian occasionwear<br/>crafted for modern celebrations.</p><a href="mailto:hello@regalemboidery.in">hello@regalemboidery.in</a></div><div><a href="#collections">Collections</a><a href="#process">Our process</a><a href="#contact">Appointments</a></div><div><p>© 2026 Regal Embroidery</p><p>regalemboidery.in</p></div></footer>
  </main>;
}
